server {
    listen 2035;
    server_name hz.jc-times.com;

    location / {
        proxy_pass http://host.docker.internal:2035; # 代理到宿主机的 2035 端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
