import { useEffect, useMemo, useState } from "react";
import { goldenSetService } from "./service";
import type { GoldenLayer, GoldenTask } from "./types";
import "./styles.css";

type Item = { item_name: string; product_family: string; product_subtype: string; item_role: string; model: string; relation: string; evidence_refs: string[] };
const packageBlank = () => ({ evidence_sufficiency: "sufficient", items: [] as Item[], notes: "" });
const erpBlank = () => ({ decision: "unique_match", acceptable_identities: [] as any[], notes: "" });
const label = (layer: GoldenLayer) => layer === "product_package" ? "产品包" : "ERP 身份";

export default function GoldenSetWorkbenchPage() {
  const [layer, setLayer] = useState<GoldenLayer>("product_package"); const [view, setView] = useState<"tasks" | "annotate" | "adjudicate">("tasks");
  const [tasks, setTasks] = useState<any>(null); const [task, setTask] = useState<GoldenTask | null>(null); const [form, setForm] = useState<any>(packageBlank()); const [message, setMessage] = useState(""); const [search, setSearch] = useState(""); const [results, setResults] = useState<any[]>([]);
  const loadTasks = async () => { try { setTasks(await goldenSetService.tasks(layer)); } catch { setMessage("任务列表加载失败"); } };
  useEffect(() => { void loadTasks(); }, [layer]);
  useEffect(() => { if (!task) return; const id = window.setTimeout(() => goldenSetService.draft(task, form).then(setTask).catch(() => setMessage("草稿未保存")), 900); return () => clearTimeout(id); }, [form, task]);
  useEffect(() => { const leave = (e: BeforeUnloadEvent) => { if (task) { e.preventDefault(); e.returnValue = ""; } }; addEventListener("beforeunload", leave); return () => removeEventListener("beforeunload", leave); }, [task]);
  const open = async (id?: string) => { try { const next = await goldenSetService.next(layer, id); setTask(next); setForm(next.annotation || (layer === "product_package" ? packageBlank() : erpBlank())); setView("annotate"); setMessage(""); } catch { setMessage("任务加载失败"); } };
  const submit = async () => { if (!task) return; try { await goldenSetService.submit(task, form); setTask(null); setView("tasks"); await loadTasks(); } catch (e: any) { setMessage(e?.response?.data?.error || "提交失败"); } };
  const addItem = () => setForm((v: any) => ({ ...v, items: [...v.items, { item_name: "", product_family: "", product_subtype: "", item_role: "平级产品", model: "", relation: "平级", evidence_refs: [task?.evidence.evidence_id] }] }));
  const updateItem = (i: number, key: keyof Item, value: string) => setForm((v: any) => ({ ...v, items: v.items.map((x: Item, n: number) => n === i ? { ...x, [key]: value } : x) }));
  const runSearch = async () => { try { const data = await goldenSetService.searchErp(search); setResults(data.items); } catch { setMessage("ERP 搜索失败"); } };
  const choose = (row: any) => setForm((v: any) => ({ ...v, acceptable_identities: [...v.acceptable_identities.filter((x: any) => `${x.company}:${x.part_num}` !== `${row.company}:${row.part_num}`), { company: row.company, part_num: row.part_num, erp_product_name: row.product_name || "", evidence_refs: [row.evidence_id] }] }));
  const instructions = useMemo(() => layer === "product_package" ? "先判断资料是否足够；可以添加多个产品。点击证据编号即可作为引用。" : "先独立搜索 ERP；Company + PartNum 才是身份，不要只按名称判断。", [layer]);
  return <main className="golden-workbench"><header><h1>Golden Set 人工标注</h1><p>{instructions}</p><nav className="qa-review-tabs"><div className="qa-review-tabs-track">{(["product_package", "erp_identity"] as GoldenLayer[]).map(v => <button className="qa-review-tab" aria-selected={layer === v} onClick={() => { setLayer(v); setView("tasks"); }}>{label(v)}</button>)}</div></nav><div className="golden-nav"><button onClick={() => setView("tasks")}>任务与进度</button><button onClick={() => void open()}>下一条</button><button onClick={() => setView("adjudicate")}>分歧复核</button></div></header>{message && <p className="golden-message">{message}</p>}
    {view === "tasks" && <section className="golden-panel"><h2>{label(layer)}任务</h2><p>已提交 {tasks?.progress?.submitted ?? 0} / {tasks?.progress?.total ?? 0}</p><div className="golden-task-list">{tasks?.items?.map((x: any) => <button onClick={() => void open(x.sample_id)} key={x.sample_id}><span>{x.status}</span>{x.sample_id}</button>)}</div></section>}
    {view === "adjudicate" && <Adjudication onBack={() => setView("tasks")} />}
    {view === "annotate" && task && <section className="golden-grid"><aside><h2>冻结证据</h2><button className="golden-evidence" onClick={() => navigator.clipboard?.writeText(task.evidence.evidence_id)}>证据编号：{task.evidence.evidence_id}</button>{task.evidence.blocks?.map((b: any) => <article key={b.evidence_id}><b>{b.section}</b><p>{b.text}</p></article>)}</aside><section><h2>{label(layer)}判断</h2><label>裁决<select value={form.evidence_sufficiency || form.decision} onChange={e => setForm((v: any) => layer === "product_package" ? { ...v, evidence_sufficiency: e.target.value } : { ...v, decision: e.target.value })}>{(layer === "product_package" ? [["sufficient","可以判断"],["legitimate_ambiguity","多种合理理解"],["insufficient_evidence","资料不足"],["abstain","无法判断"]] : [["unique_match","唯一匹配"],["legitimate_ambiguity","多个合理"],["insufficient_evidence","证据不足"],["abstain","无法判断"]]).map(([v,t]) => <option value={v}>{t}</option>)}</select></label>
      {layer === "product_package" ? <><button onClick={addItem}>添加产品</button>{form.items.map((item: Item, i: number) => <div className="golden-card" key={i}><input placeholder="产品名称" value={item.item_name} onChange={e => updateItem(i,"item_name",e.target.value)} /><input placeholder="family" value={item.product_family} onChange={e => updateItem(i,"product_family",e.target.value)} /><input placeholder="subtype" value={item.product_subtype} onChange={e => updateItem(i,"product_subtype",e.target.value)} /><input placeholder="model" value={item.model} onChange={e => updateItem(i,"model",e.target.value)} /><select value={item.relation} onChange={e => updateItem(i,"relation",e.target.value)}>{["平级","附件组件","销售套件","不确定"].map(x => <option>{x}</option>)}</select></div>)}</> : <><div className="golden-search"><input placeholder="输入产品名称或编号" value={search} onChange={e => setSearch(e.target.value)} /><button onClick={() => void runSearch()}>搜索 ERP</button></div>{results.map(r => <button className="golden-erp" onClick={() => choose(r)} key={`${r.company}:${r.part_num}`}>{r.company} + {r.part_num}　{r.product_name || "无名称"}　{r.prod_code || ""}</button>)}</>}
      <label>说明<textarea value={form.notes || ""} onChange={e => setForm((v: any) => ({ ...v, notes: e.target.value }))}/></label><footer><button onClick={() => setView("tasks")}>稍后处理</button><button onClick={() => void submit()}>保存并下一条</button></footer></section></section>}</main>;
}

function Adjudication({ onBack }: { onBack: () => void }) { const [items, setItems] = useState<any[]>([]); useEffect(() => { goldenSetService.adjudications().then(v => setItems(v.items)).catch(() => {}); }, []); return <section className="golden-panel"><h2>仅显示 A/B 分歧</h2>{!items.length && <p>当前没有待复核分歧。</p>}{items.map(x => <article className="golden-card" key={x.sample_id}><b>{x.sample_id}</b><p>A：{JSON.stringify(x.annotator_a)}</p><p>B：{JSON.stringify(x.annotator_b)}</p><button>采用 A</button><button>采用 B</button><button>编辑第三答案</button><button>真正歧义</button><button>证据不足</button></article>)}<button onClick={onBack}>返回任务</button></section>; }
