import { useEffect, useState } from "react";
import { goldenSetService } from "./service";
import type { GoldenLayer, GoldenTask } from "./types";
import "./styles.css";
const emptyPackage = { evidence_sufficiency: "sufficient", items: [], notes: null };
const emptyErp = { decision: "unique_match", acceptable_identities: [], notes: null };
export default function GoldenSetWorkbenchPage() {
  const [layer, setLayer] = useState<GoldenLayer>("product_package"); const [task, setTask] = useState<GoldenTask | null>(null); const [annotation, setAnnotation] = useState<any>(emptyPackage); const [message, setMessage] = useState("正在加载任务…");
  const load = async () => { try { const next = await goldenSetService.next(layer); if (!next?.evidence || !next?.sample_id) throw new Error("无法获取标注任务，请确认已登录且拥有标注席位"); setTask(next); setAnnotation(next.annotation || (layer === "product_package" ? emptyPackage : emptyErp)); setMessage(""); } catch (e: any) { setTask(null); setMessage(e?.message || "任务加载失败"); } };
  useEffect(() => { void load(); }, [layer]);
  useEffect(() => { const timer = window.setTimeout(() => { if (task) goldenSetService.draft(task, annotation).then(setTask).catch(() => setMessage("草稿未保存")); }, 1200); return () => window.clearTimeout(timer); }, [annotation]);
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (task) { e.preventDefault(); e.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [task]);
  const saveNext = async () => { if (!task) return; try { await goldenSetService.submit(task, annotation); await load(); } catch (e: any) { setMessage(e?.response?.data?.error || "提交失败"); } };
  return <main className="golden-workbench"><header><h1>Golden Set 人工标注</h1><p>只根据左侧证据判断。系统结果和另一位标注员答案不会显示。</p><div className="qa-review-tabs"><div className="qa-review-tabs-track">{(["product_package", "erp_identity"] as GoldenLayer[]).map(v => <button className="qa-review-tab" aria-selected={layer === v} onClick={() => setLayer(v)} key={v}>{v === "product_package" ? "产品包" : "ERP 身份"}</button>)}</div></div></header>{message && <p className="golden-message">{message}</p>}{task && <section className="golden-grid"><aside><h2>冻结证据</h2><p><b>证据编号：</b>{task.evidence.evidence_id}</p>{Object.entries(task.evidence.source).map(([k,v]) => <p key={k}><b>{k}：</b>{String(v)}</p>)}{task.evidence.erp_candidates.map(c => <button className="golden-erp" key={c.evidence_id} onClick={() => setAnnotation((a:any) => ({ ...a, acceptable_identities: [...(a.acceptable_identities || []), { company:c.company, part_num:c.part_num, erp_product_name:c.product_name || "", evidence_refs:[c.evidence_id] }] }))}>{c.company} + {c.part_num} {c.product_name || "未提供名称"}</button>)}</aside><section><h2>{layer === "product_package" ? "产品包判断" : "ERP 身份判断"}</h2><label>裁决<select value={annotation.evidence_sufficiency || annotation.decision} onChange={e => setAnnotation((a:any) => layer === "product_package" ? {...a,evidence_sufficiency:e.target.value} : {...a,decision:e.target.value})}>{(layer === "product_package" ? [["sufficient","可以判断"],["legitimate_ambiguity","多种合理理解"],["insufficient_evidence","资料不足"],["abstain","无法判断"]] : [["unique_match","唯一匹配"],["legitimate_ambiguity","多个合理"],["insufficient_evidence","证据不足"],["abstain","无法判断"]]).map(([v,t]) => <option value={v} key={v}>{t}</option>)}</select></label>{layer === "product_package" && <><label>产品名称<input onChange={e => setAnnotation((a:any) => ({...a, items:[{ gold_item_id:"item-1",matched_prediction_item_id:null,item_name:e.target.value,product_family:null,product_subtype:null,item_role:"peer_product",model:null,peer_group_id:null,related_to_gold_item_id:null,evidence_refs:[task.evidence.evidence_id]}]}))}/></label><p className="golden-help">多个产品请分别添加；关系使用平级、附件组件、销售套件或不确定。</p></>}<label>说明<textarea value={annotation.notes || ""} onChange={e => setAnnotation((a:any) => ({...a,notes:e.target.value || null}))}/></label><footer><button className="qa-btn qa-btn-secondary" onClick={load}>稍后处理</button><button className="qa-btn qa-btn-primary" onClick={saveNext}>保存并下一条</button></footer></section></section>}</main>;
}
