import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const baseline = process.env.PRODUCT_CONFIG_GOLDEN_SET_BASELINE_DIR || "/Users/zzzsaft/.codex/worktrees/6054/jc-hub/tmp/product-config-golden-set-v1";
const output = process.env.PRODUCT_CONFIG_GOLDEN_SET_EVIDENCE_DIR || path.join(process.cwd(), "tmp/product-config-golden-set-v1-evidence");
const hash = (v: Buffer | string) => crypto.createHash("sha256").update(v).digest("hex");
const json = (name: string) => JSON.parse(fs.readFileSync(path.join(baseline, name), "utf8"));
const redact = (value: unknown): unknown => Array.isArray(value) ? value.map(redact) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value as Record<string, unknown>).filter(([k]) => !/file|customer|contact|phone|address|price|bom.*detail/i.test(k)).map(([k,v]) => [k, redact(v)])) : value;
const packages = json("product-package-annotation-packets.json"); const erp = json("erp-identity-annotation-packets.json");
const snapshot = { schema_version: "product-config-golden-evidence-snapshot-v1", read_only: true, input_hash: hash(JSON.stringify({ packages: packages.map((v:any) => v.sample_id), erp: erp.map((v:any) => v.sample_id) })), packages: packages.map((p:any) => ({ sample_id:p.sample_id, evidence_id:`evidence:${p.sample_id}`, source:redact(p.source), strata:p.strata, selection_reasons:p.selection_reasons, blocks:[] })), erp: erp.map((p:any) => ({ sample_id:p.sample_id, evidence_id:`evidence:${p.sample_id}`, source:redact(p.source), strata:p.strata, erp_candidates:(p.prediction.top_candidates || []).map((c:any,i:number) => ({ evidence_id:`erp-${i+1}`, company:c.company, part_num:c.part_num, erp_product_name:c.erp_product_name, prod_code:c.prod_code, has_bom:c.has_bom, has_order_evidence:Boolean(c.erp_order_num) })) })) };
if (snapshot.packages.length !== 160 || snapshot.erp.length !== 240) throw new Error("sample conservation failed");
fs.mkdirSync(output, { recursive:true }); const content = JSON.stringify(snapshot, null, 2); fs.writeFileSync(path.join(output,"evidence-snapshot.json"), content); const pilot = { schema_version:"product-config-golden-pilot-v1", read_only:true, package_sample_ids:snapshot.packages.slice(0,20).map((v: { sample_id: string })=>v.sample_id), erp_sample_ids:snapshot.erp.slice(0,30).map((v: { sample_id: string })=>v.sample_id), instruction:"仅创建固定试标清单；不得代填人工答案。" }; const pilotContent=JSON.stringify(pilot,null,2); fs.writeFileSync(path.join(output,"pilot-task-list.json"), pilotContent); const seal = { schema_version:"product-config-golden-evidence-seal-v1", immutable:true, input_hash:snapshot.input_hash, artifacts:{"evidence-snapshot.json":{sha256:hash(content),bytes:Buffer.byteLength(content)},"pilot-task-list.json":{sha256:hash(pilotContent),bytes:Buffer.byteLength(pilotContent)}} }; fs.writeFileSync(path.join(output,"artifact-seal.json"), JSON.stringify(seal,null,2)); console.log(`evidence snapshot: package=${snapshot.packages.length} erp=${snapshot.erp.length} sealed=${output}`);
