export { requireProductConfigAgentAdmin, requireProductConfigAgentToken } from "./auth.js";
import { withFullReviewAdjudicator, withFullReviewAnnotator, withProductConfigAgentAdmin, withProductConfigAgentToken } from "./auth.js";
import {
  createShareToken,
  getAgentSession,
  getGeneratedConfig,
  getSharedGeneratedConfig,
  listAgentSessions,
  revokeShareToken,
  runAgent,
} from "./handlers/agentHandlers.js";
import {
  archiveDocument,
  checkArchiveReadiness,
  createContractArchive,
  getContractArchive,
  getContractArchiveSnapshot,
  getContractArchiveVersion,
  listContractArchives,
  listContractArchiveVersions,
  patchContractArchive,
  replaceArchiveItemProductBindings,
  searchProductConfigs,
} from "./handlers/archiveHandlers.js";
import {
  applyConceptPatternCandidates,
  approveCandidateAsAlias,
  approveUnitCandidate,
  candidateReviewPrompt,
  createDictionaryHealthReport,
  createTermType,
  createTermTypeFromCandidate,
  createUnitAlias,
  createValue,
  createValueFromCandidate,
  deleteTermType,
  deleteUnitAlias,
  deleteValue,
  dictionaryHealthAuditJobs,
  generateCandidates,
  getConceptResolverRun,
  listCandidateClusters,
  listCandidateSuggestions,
  listCandidates,
  listConceptPatterns,
  listConceptResolutions,
  listDictionaryHealthReports,
  listSplits,
  listTermTypes,
  listUnitAliases,
  listUnitCandidates,
  listValues,
  markCandidateAsDocInfo,
  moveCandidateToTermType,
  rejectCandidate,
  rejectUnitCandidate,
  reviewCandidate,
  reviewCandidatesBatch,
  reviewConceptPattern,
  runConceptResolver,
  splitCandidate,
  suggestCandidatesBatch,
  unitCandidatesReviewPrompt,
  updateCandidateTermTypeKind,
  updateTermType,
  updateValue,
} from "./handlers/dictionaryHandlers.js";
import {
  contractsSummary,
  dictionaryDirtyRefreshStatus,
  getDocument,
  getExtraction,
  getJob,
  listBackgroundJobs,
  listDocuments,
  listExtractions,
  llmSummary,
  openDocumentFile,
  parseBlocksBatch,
  pendingLlmStatus,
  reextract,
  renormalizeExtraction,
  renormalizeExtractionResult,
  renormalizeExtractionsBatch,
  saveBlocks,
  startDictionaryDirtyRefresh,
  startPendingLlmBatch,
  uploadContract,
} from "./handlers/documentHandlers.js";
import { masterDataModelBinding, masterDataModelBindingPost } from "./handlers/masterDataHandlers.js";
import { exportGoldenAnnotations, goldenAdjudicationQueue, goldenTask, goldenTasks, saveGoldenDraft, submitGoldenAdjudication, submitGoldenTask } from "./handlers/goldenSetAnnotationHandlers.js";
import { exportFullReviewAnnotations, fullReviewAdjudications, fullReviewTasks, previewFullReviewAdmission, saveFullReviewDraft, submitFullReviewAdjudication, submitFullReviewTask } from "./handlers/goldenSetFullReviewHandlers.js";

export const ProductConfigAgentRoutes = [
  { path: "/productConfigAgent/golden-set-v2/tasks", method: "get", auth: "annotator", action: withFullReviewAnnotator(fullReviewTasks) },
  { path: "/productConfigAgent/golden-set-v2/tasks/:documentId/draft", method: "put", auth: "annotator", action: withFullReviewAnnotator(saveFullReviewDraft) },
  { path: "/productConfigAgent/golden-set-v2/tasks/:documentId/submit", method: "post", auth: "annotator", action: withFullReviewAnnotator(submitFullReviewTask) },
  { path: "/productConfigAgent/golden-set-v2/adjudications", method: "get", auth: "adjudicator", action: withFullReviewAdjudicator(fullReviewAdjudications) },
  { path: "/productConfigAgent/golden-set-v2/adjudications/:documentId", method: "post", auth: "adjudicator", action: withFullReviewAdjudicator(submitFullReviewAdjudication) },
  { path: "/productConfigAgent/golden-set-v2/export", method: "get", auth: "adjudicator", action: withFullReviewAdjudicator(exportFullReviewAnnotations) },
  { path: "/productConfigAgent/golden-set-v2/admission-preview", method: "post", auth: "adjudicator", action: withFullReviewAdjudicator(previewFullReviewAdmission) },
  { path: "/productConfigAgent/golden-set/tasks", method: "get", action: withProductConfigAgentToken(goldenTasks) },
  { path: "/productConfigAgent/golden-set/tasks/:sampleId", method: "get", action: withProductConfigAgentToken(goldenTask) },
  { path: "/productConfigAgent/golden-set/tasks/:sampleId/draft", method: "put", action: withProductConfigAgentToken(saveGoldenDraft) },
  { path: "/productConfigAgent/golden-set/tasks/:sampleId/submit", method: "post", action: withProductConfigAgentToken(submitGoldenTask) },
  { path: "/productConfigAgent/golden-set/adjudications", method: "get", action: withProductConfigAgentAdmin(goldenAdjudicationQueue) },
  { path: "/productConfigAgent/golden-set/adjudications/:sampleId", method: "post", action: withProductConfigAgentAdmin(submitGoldenAdjudication) },
  { path: "/productConfigAgent/golden-set/export", method: "get", action: withProductConfigAgentAdmin(exportGoldenAnnotations) },
  { path: "/productConfigAgent/agent/sessions", method: "get", action: withProductConfigAgentToken(listAgentSessions) },
  { path: "/productConfigAgent/agent/run", method: "post", action: withProductConfigAgentToken(runAgent) },
  { path: "/productConfigAgent/agent/sessions/:sessionId", method: "get", action: withProductConfigAgentToken(getAgentSession) },
  { path: "/productConfigAgent/agent/configs/:id/share-token", method: "post", action: withProductConfigAgentToken(createShareToken) },
  { path: "/productConfigAgent/agent/configs/:id/share-token/revoke", method: "post", action: withProductConfigAgentToken(revokeShareToken) },
  { path: "/productConfigAgent/agent/configs/:id", method: "get", action: withProductConfigAgentToken(getGeneratedConfig) },
  { path: "/productConfigAgent/agent/shared/:shareToken", method: "get", action: getSharedGeneratedConfig },
  { path: "/productConfigAgent/contracts/upload", method: "post", action: withProductConfigAgentAdmin(uploadContract) },
  { path: "/productConfigAgent/contracts/summary", method: "get", action: withProductConfigAgentToken(contractsSummary) },
  { path: "/productConfigAgent/contracts", method: "get", action: withProductConfigAgentToken(listDocuments) },
  { path: "/productConfigAgent/contracts/:documentId/candidates/generate", method: "post", action: withProductConfigAgentAdmin(generateCandidates) },
  { path: "/productConfigAgent/contracts/:documentId", method: "get", action: withProductConfigAgentToken(getDocument) },
  { path: "/productConfigAgent/contracts/:documentId/blocks", method: "put", action: withProductConfigAgentAdmin(saveBlocks) },
  { path: "/productConfigAgent/documents/:documentId/open-file", method: "get", action: withProductConfigAgentToken(openDocumentFile) },
  { path: "/productConfigAgent/extractions", method: "get", action: withProductConfigAgentToken(listExtractions) },
  { path: "/productConfigAgent/extractions/llm-summary", method: "get", action: withProductConfigAgentToken(llmSummary) },
  { path: "/api/extractions", method: "get", action: withProductConfigAgentToken(listExtractions) },
  { path: "/api/extractions/llm-summary", method: "get", action: withProductConfigAgentToken(llmSummary) },
  { path: "/productConfigAgent/extractions/renormalize-batch", method: "post", action: withProductConfigAgentAdmin(renormalizeExtractionsBatch) },
  { path: "/productConfigAgent/extractions/:documentId", method: "get", action: withProductConfigAgentToken(getExtraction) },
  { path: "/api/extractions/:documentId", method: "get", action: withProductConfigAgentToken(getExtraction) },
  { path: "/productConfigAgent/extractions/:documentId/reextract", method: "post", action: withProductConfigAgentAdmin(reextract) },
  { path: "/api/extractions/:documentId/reextract", method: "post", action: withProductConfigAgentAdmin(reextract) },
  { path: "/productConfigAgent/extractions/:documentId/renormalize", method: "post", action: withProductConfigAgentAdmin(renormalizeExtraction) },
  { path: "/api/extractions/:documentId/renormalize", method: "post", action: withProductConfigAgentAdmin(renormalizeExtraction) },
  { path: "/productConfigAgent/extraction-results/:extractionResultId/renormalize", method: "post", action: withProductConfigAgentAdmin(renormalizeExtractionResult) },
  { path: "/api/extraction-results/:extractionResultId/renormalize", method: "post", action: withProductConfigAgentAdmin(renormalizeExtractionResult) },
  { path: "/productConfigAgent/dictionary/term-types", method: "get", action: withProductConfigAgentToken(listTermTypes) },
  { path: "/productConfigAgent/dictionary/term-types", method: "post", action: withProductConfigAgentAdmin(createTermType) },
  { path: "/productConfigAgent/dictionary/term-types/:id", method: "put", action: withProductConfigAgentAdmin(updateTermType) },
  { path: "/productConfigAgent/dictionary/term-types/:id", method: "delete", action: withProductConfigAgentAdmin(deleteTermType) },
  { path: "/productConfigAgent/dictionary/values", method: "get", action: withProductConfigAgentToken(listValues) },
  { path: "/productConfigAgent/dictionary/values", method: "post", action: withProductConfigAgentAdmin(createValue) },
  { path: "/productConfigAgent/dictionary/values/:id", method: "put", action: withProductConfigAgentAdmin(updateValue) },
  { path: "/productConfigAgent/dictionary/values/:id", method: "delete", action: withProductConfigAgentAdmin(deleteValue) },
  { path: "/productConfigAgent/dictionary/unit-aliases", method: "get", action: withProductConfigAgentToken(listUnitAliases) },
  { path: "/productConfigAgent/dictionary/unit-aliases", method: "post", action: withProductConfigAgentAdmin(createUnitAlias) },
  { path: "/productConfigAgent/dictionary/unit-aliases/:id", method: "delete", action: withProductConfigAgentAdmin(deleteUnitAlias) },
  { path: "/api/dictionary/product-types", method: "get", action: withProductConfigAgentToken(listTermTypes) },
  { path: "/productConfigAgent/documents/pending-llm-upload/status", method: "get", action: withProductConfigAgentToken(pendingLlmStatus) },
  { path: "/productConfigAgent/documents/pending-llm-upload/start", method: "post", action: withProductConfigAgentAdmin(startPendingLlmBatch) },
  { path: "/productConfigAgent/workflows/parse-blocks-batch", method: "post", action: withProductConfigAgentAdmin(parseBlocksBatch) },
  { path: "/productConfigAgent/dictionary-dirty/refresh/start", method: "post", action: withProductConfigAgentAdmin(startDictionaryDirtyRefresh) },
  { path: "/productConfigAgent/dictionary-dirty/refresh/status", method: "get", action: withProductConfigAgentToken(dictionaryDirtyRefreshStatus) },
  { path: "/productConfigAgent/candidates", method: "get", action: withProductConfigAgentToken(listCandidates) },
  { path: "/productConfigAgent/candidates/suggestions", method: "get", action: withProductConfigAgentToken(listCandidateSuggestions) },
  { path: "/productConfigAgent/candidates/suggestions/batch", method: "post", action: withProductConfigAgentAdmin(suggestCandidatesBatch) },
  { path: "/productConfigAgent/candidates/clusters/review-prompt", method: "get", action: withProductConfigAgentToken(candidateReviewPrompt) },
  { path: "/productConfigAgent/candidates/clusters", method: "get", action: withProductConfigAgentToken(listCandidateClusters) },
  { path: "/productConfigAgent/candidates/clusters/suggestions/batch", method: "post", action: withProductConfigAgentAdmin(suggestCandidatesBatch) },
  { path: "/productConfigAgent/candidates/reviews/batch", method: "post", action: withProductConfigAgentAdmin(reviewCandidatesBatch) },
  { path: "/productConfigAgent/candidates/splits", method: "get", action: withProductConfigAgentToken(listSplits) },
  { path: "/productConfigAgent/candidates/units", method: "get", action: withProductConfigAgentToken(listUnitCandidates) },
  { path: "/productConfigAgent/candidates/units/review-prompt", method: "get", action: withProductConfigAgentToken(unitCandidatesReviewPrompt) },
  { path: "/productConfigAgent/candidates/units/:candidateId/approve", method: "post", action: withProductConfigAgentAdmin(approveUnitCandidate) },
  { path: "/productConfigAgent/candidates/units/:candidateId/reject", method: "post", action: withProductConfigAgentAdmin(rejectUnitCandidate) },
  { path: "/productConfigAgent/candidates/:candidateId/review", method: "post", action: withProductConfigAgentAdmin(reviewCandidate) },
  { path: "/productConfigAgent/candidates/term-type/:candidateId/create-term-type", method: "post", action: withProductConfigAgentAdmin(createTermTypeFromCandidate) },
  { path: "/productConfigAgent/candidates/term-type/:candidateId/suggest", method: "post", action: withProductConfigAgentAdmin(createTermTypeFromCandidate) },
  { path: "/productConfigAgent/candidates/term-type/:candidateId/approve-as-alias", method: "post", action: withProductConfigAgentAdmin(approveCandidateAsAlias) },
  { path: "/productConfigAgent/candidates/value/:candidateId/split", method: "post", action: withProductConfigAgentAdmin(splitCandidate) },
  { path: "/productConfigAgent/candidates/term-type/:candidateId/split", method: "post", action: withProductConfigAgentAdmin(splitCandidate) },
  { path: "/productConfigAgent/candidates/term-type/:candidateId/mark-as-doc-info", method: "post", action: withProductConfigAgentAdmin(markCandidateAsDocInfo) },
  { path: "/productConfigAgent/candidates/value/:candidateId/create-value", method: "post", action: withProductConfigAgentAdmin(createValueFromCandidate) },
  { path: "/productConfigAgent/candidates/value/:candidateId/split-suggest", method: "post", action: withProductConfigAgentAdmin(splitCandidate) },
  { path: "/productConfigAgent/candidates/value/:candidateId/move-to-term-type", method: "post", action: withProductConfigAgentAdmin(moveCandidateToTermType) },
  { path: "/productConfigAgent/candidates/value/:candidateId/approve-as-alias", method: "post", action: withProductConfigAgentAdmin(approveCandidateAsAlias) },
  { path: "/productConfigAgent/candidates/value/:candidateId/update-term-type-kind", method: "post", action: withProductConfigAgentAdmin(updateCandidateTermTypeKind) },
  { path: "/productConfigAgent/candidates/:type/:candidateId/reject", method: "post", action: withProductConfigAgentAdmin(rejectCandidate) },
  { path: "/productConfigAgent/concept-resolver/run", method: "post", action: withProductConfigAgentAdmin(runConceptResolver) },
  { path: "/productConfigAgent/concept-resolver/runs/:runId", method: "get", action: withProductConfigAgentToken(getConceptResolverRun) },
  { path: "/productConfigAgent/concept-resolver/resolutions", method: "get", action: withProductConfigAgentToken(listConceptResolutions) },
  { path: "/productConfigAgent/concept-resolver/patterns", method: "get", action: withProductConfigAgentToken(listConceptPatterns) },
  { path: "/productConfigAgent/concept-resolver/patterns/:id/review", method: "post", action: withProductConfigAgentAdmin(reviewConceptPattern) },
  { path: "/productConfigAgent/concept-resolver/patterns/:id/apply-candidates", method: "post", action: withProductConfigAgentAdmin(applyConceptPatternCandidates) },
  { path: "/productConfigAgent/dictionary/health/audit", method: "post", action: withProductConfigAgentAdmin(createDictionaryHealthReport) },
  { path: "/productConfigAgent/dictionary/health-audit/jobs", method: "get", action: withProductConfigAgentToken(dictionaryHealthAuditJobs) },
  { path: "/productConfigAgent/dictionary/health-report", method: "get", action: withProductConfigAgentToken(listDictionaryHealthReports) },
  { path: "/productConfigAgent/jobs/:jobId", method: "get", action: withProductConfigAgentToken(getJob) },
  { path: "/productConfigAgent/background-jobs", method: "get", action: withProductConfigAgentToken(listBackgroundJobs) },
  { path: "/productConfigAgent/background-jobs/:jobId", method: "get", action: withProductConfigAgentToken(getJob) },
  { path: "/productConfigAgent/master-data/model-binding", method: "get", action: withProductConfigAgentToken(masterDataModelBinding) },
  { path: "/productConfigAgent/master-data/model-binding", method: "post", action: withProductConfigAgentAdmin(masterDataModelBindingPost) },
  { path: "/productConfigAgent/contract-archives", method: "get", action: withProductConfigAgentToken(listContractArchives) },
  { path: "/productConfigAgent/contract-archives", method: "post", action: withProductConfigAgentAdmin(createContractArchive) },
  { path: "/productConfigAgent/contracts/:documentId/archive", method: "post", action: withProductConfigAgentAdmin(archiveDocument) },
  { path: "/productConfigAgent/contracts/:documentId/archive-readiness", method: "get", action: withProductConfigAgentToken(checkArchiveReadiness) },
  { path: "/productConfigAgent/contract-archives/:archiveId", method: "get", action: withProductConfigAgentToken(getContractArchive) },
  { path: "/productConfigAgent/contract-archives/:archiveId/snapshot", method: "get", action: withProductConfigAgentToken(getContractArchiveSnapshot) },
  { path: "/productConfigAgent/contract-archives/:archiveId", method: "patch", action: withProductConfigAgentAdmin(patchContractArchive) },
  { path: "/productConfigAgent/contract-archives/:archiveId/versions", method: "get", action: withProductConfigAgentToken(listContractArchiveVersions) },
  { path: "/productConfigAgent/contract-archives/:archiveId/versions/:version", method: "get", action: withProductConfigAgentToken(getContractArchiveVersion) },
  { path: "/productConfigAgent/contract-archives/:archiveId/items/:itemId/product-bindings", method: "put", action: withProductConfigAgentAdmin(replaceArchiveItemProductBindings) },
  { path: "/productConfigAgent/product-configs/search", method: "get", action: withProductConfigAgentToken(searchProductConfigs) },
];

export const LegacyProductConfigAgentRoutes = ProductConfigAgentRoutes.map((route) => ({
  ...route,
  path: legacyProductConfigAgentRoutePath(route.path),
}));

function legacyProductConfigAgentRoutePath(routePath: string): string {
  if (routePath.startsWith("/productConfigAgent")) {
    return routePath.replace("/productConfigAgent", "/quoteAgent");
  }
  return routePath;
}
